include: package:flutter_lints/flutter.yaml

dcm:
  extends:
    - recommended
  metrics:
    cyclomatic-complexity:
      threshold: 10
    lines-of-code:
      threshold: 40
    number-of-parameters:
      threshold: 5
    maximum-nesting-level:
      threshold: 3
