/// Lower-cased extension → `flutter_highlight` language id.
///
/// Returns `'plaintext'` for anything not in the table; that language id
/// is special-cased in [CodeBlockBuilder] to skip the language label.
String languageForExtension(String extension) =>
    _languageByExtension[extension.toLowerCase()] ?? 'plaintext';

const _languageByExtension = <String, String>{
  'dart': 'dart',
  'py': 'python',
  'js': 'javascript',
  'mjs': 'javascript',
  'cjs': 'javascript',
  'ts': 'typescript',
  'tsx': 'typescript',
  'jsx': 'javascript',
  'go': 'go',
  'rs': 'rust',
  'java': 'java',
  'kt': 'kotlin',
  'kts': 'kotlin',
  'swift': 'swift',
  'c': 'c',
  'cc': 'cpp',
  'cpp': 'cpp',
  'cxx': 'cpp',
  'h': 'c',
  'hh': 'cpp',
  'hpp': 'cpp',
  'cs': 'csharp',
  'rb': 'ruby',
  'php': 'php',
  'sh': 'bash',
  'bash': 'bash',
  'zsh': 'bash',
  'fish': 'bash',
  'ps1': 'powershell',
  'r': 'r',
  'scala': 'scala',
  'lua': 'lua',
  'pl': 'perl',
  'sql': 'sql',
  'yaml': 'yaml',
  'yml': 'yaml',
  'toml': 'ini',
  'xml': 'xml',
  'html': 'xml',
  'htm': 'xml',
  'svg': 'xml',
  'gradle': 'groovy',
  'groovy': 'groovy',
  'makefile': 'makefile',
  'dockerfile': 'dockerfile',
  'json': 'json',
  'csv': 'plaintext',
  'tsv': 'plaintext',
};
